//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mpal.Compiler {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mpal.Compiler.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1001: Cannot implicitly convert type &apos;{0}&apos; to &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string C1001 {
            get {
                return ResourceManager.GetString("C1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1002: Undefined symbol &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string C1002 {
            get {
                return ResourceManager.GetString("C1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1003: Into a constant cannot be written ähnelt.
        /// </summary>
        internal static string C1003 {
            get {
                return ResourceManager.GetString("C1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1004: Operation is not defined for &apos;{0}&apos; and &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string C1004 {
            get {
                return ResourceManager.GetString("C1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1004: Operation is not defined for &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string C1004_1 {
            get {
                return ResourceManager.GetString("C1004_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1005: The integer constant is to large ähnelt.
        /// </summary>
        internal static string C1005 {
            get {
                return ResourceManager.GetString("C1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1006: The real constant is to large ähnelt.
        /// </summary>
        internal static string C1006 {
            get {
                return ResourceManager.GetString("C1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1007: The IF or ELSIF condition must have the type BOOL ähnelt.
        /// </summary>
        internal static string C1007 {
            get {
                return ResourceManager.GetString("C1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1008: &apos;{0}&apos; is not a member of &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string C1008 {
            get {
                return ResourceManager.GetString("C1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1009: &apos;{0}&apos; is not a structured type and cannot by selected ähnelt.
        /// </summary>
        internal static string C1009 {
            get {
                return ResourceManager.GetString("C1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1010: &apos;{0}&apos; is not an array type and cannot by selected ähnelt.
        /// </summary>
        internal static string C1010 {
            get {
                return ResourceManager.GetString("C1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1011: To many index parameter for &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string C1011 {
            get {
                return ResourceManager.GetString("C1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1012: The index &apos;{0}&apos; is out of range ähnelt.
        /// </summary>
        internal static string C1012 {
            get {
                return ResourceManager.GetString("C1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1013: The function call &apos;{0}&apos; has to many parameter ähnelt.
        /// </summary>
        internal static string C1013 {
            get {
                return ResourceManager.GetString("C1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1014: The explicit parameter assignment for the function &apos;{0}&apos; is not supported ähnelt.
        /// </summary>
        internal static string C1014 {
            get {
                return ResourceManager.GetString("C1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1015: A constant cannot be incremented or decremented ähnelt.
        /// </summary>
        internal static string C1015 {
            get {
                return ResourceManager.GetString("C1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1016: Only variables can be incremented or decremented ähnelt.
        /// </summary>
        internal static string C1016 {
            get {
                return ResourceManager.GetString("C1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1017: The array indexing is not complete, the &apos;{0}&apos; cannot be selected ähnelt.
        /// </summary>
        internal static string C1017 {
            get {
                return ResourceManager.GetString("C1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1018: Only integer type can be used as case variable ähnelt.
        /// </summary>
        internal static string C1018 {
            get {
                return ResourceManager.GetString("C1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1019: &apos;{0}&apos; is not a constant, only constants can be used as case ähnelt.
        /// </summary>
        internal static string C1019 {
            get {
                return ResourceManager.GetString("C1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1020: &apos;{0}&apos; is not an integer constant, only integer can be used as case ähnelt.
        /// </summary>
        internal static string C1020 {
            get {
                return ResourceManager.GetString("C1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1021: The case in the line &apos;{0}&apos; has one or more values identical with the values of case in the line &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string C1021 {
            get {
                return ResourceManager.GetString("C1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1022: &apos;{0}&apos; is not an integer, only an integer can be used as for variable ähnelt.
        /// </summary>
        internal static string C1022 {
            get {
                return ResourceManager.GetString("C1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1023: An integer data type for the final variable is expected ähnelt.
        /// </summary>
        internal static string C1023 {
            get {
                return ResourceManager.GetString("C1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1024: EXIT statement can only be used into a loop statement ähnelt.
        /// </summary>
        internal static string C1024 {
            get {
                return ResourceManager.GetString("C1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1025: CONTINUE statement can only be used into a loop statement ähnelt.
        /// </summary>
        internal static string C1025 {
            get {
                return ResourceManager.GetString("C1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1026: The condition of the while statement must have the type BOOL ähnelt.
        /// </summary>
        internal static string C1026 {
            get {
                return ResourceManager.GetString("C1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1027: Only floating point numbers can be rounded or truncated ähnelt.
        /// </summary>
        internal static string C1027 {
            get {
                return ResourceManager.GetString("C1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1028: Only numeric type is accepted by the &apos;{0}&apos; function ähnelt.
        /// </summary>
        internal static string C1028 {
            get {
                return ResourceManager.GetString("C1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1029: Only bit string type is accepted by the &apos;{0}&apos; function ähnelt.
        /// </summary>
        internal static string C1029 {
            get {
                return ResourceManager.GetString("C1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1030: Wrong number of parameter for the function &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string C1030 {
            get {
                return ResourceManager.GetString("C1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1031: Wrong parameter assignment for the function &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string C1031 {
            get {
                return ResourceManager.GetString("C1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1032: IN parameter for the bit string function &apos;{0}&apos; is missing ähnelt.
        /// </summary>
        internal static string C1032 {
            get {
                return ResourceManager.GetString("C1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1033: N parameter for the bit string function &apos;{0}&apos; is missing ähnelt.
        /// </summary>
        internal static string C1033 {
            get {
                return ResourceManager.GetString("C1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1034: Bit string function &apos;{0}&apos; is not defined for the type &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string C1034 {
            get {
                return ResourceManager.GetString("C1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1035: The function &apos;{0}&apos; is not defined ähnelt.
        /// </summary>
        internal static string C1035 {
            get {
                return ResourceManager.GetString("C1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1036: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; cannot be assigned ähnelt.
        /// </summary>
        internal static string C1036 {
            get {
                return ResourceManager.GetString("C1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1037: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; is not defined ähnelt.
        /// </summary>
        internal static string C1037 {
            get {
                return ResourceManager.GetString("C1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1038: Wrong parameter assignment for the parameter&apos;{0}&apos; of the function &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string C1038 {
            get {
                return ResourceManager.GetString("C1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1039: To many parameter for the function &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string C1039 {
            get {
                return ResourceManager.GetString("C1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1040: The function &apos;{0}&apos; accept only one parameter ähnelt.
        /// </summary>
        internal static string C1040 {
            get {
                return ResourceManager.GetString("C1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1041: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; is an output parameter and cannot be assigned to a constant ähnelt.
        /// </summary>
        internal static string C1041 {
            get {
                return ResourceManager.GetString("C1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1042: The return value of the function &apos;{0}&apos; is not used ähnelt.
        /// </summary>
        internal static string C1042 {
            get {
                return ResourceManager.GetString("C1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die :error C1043: The selector of the function SEL must have the type BOOL ähnelt.
        /// </summary>
        internal static string C1043 {
            get {
                return ResourceManager.GetString("C1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die :error C1044: The MAX, MIN functions accept only numeric parameter ähnelt.
        /// </summary>
        internal static string C1044 {
            get {
                return ResourceManager.GetString("C1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die :error C1045: The parameter of the MUX function must have the same type ähnelt.
        /// </summary>
        internal static string C1045 {
            get {
                return ResourceManager.GetString("C1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die :error C1046: The parameter K of the function MUX must have the type integer ähnelt.
        /// </summary>
        internal static string C1046 {
            get {
                return ResourceManager.GetString("C1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1047: Only function blocks can be used as type ähnelt.
        /// </summary>
        internal static string C1047 {
            get {
                return ResourceManager.GetString("C1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1048: The function block &apos;{0}&apos; must be instantiate before use ähnelt.
        /// </summary>
        internal static string C1048 {
            get {
                return ResourceManager.GetString("C1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1049: The member &apos;{0}&apos; of the function block &apos;{1}&apos; can not be access ähnelt.
        /// </summary>
        internal static string C1049 {
            get {
                return ResourceManager.GetString("C1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1050: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; is an output parameter and cannot be assigned ähnelt.
        /// </summary>
        internal static string C1050 {
            get {
                return ResourceManager.GetString("C1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1051: Division by constant zero ähnelt.
        /// </summary>
        internal static string C1051 {
            get {
                return ResourceManager.GetString("C1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1052: The function &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string C1052 {
            get {
                return ResourceManager.GetString("C1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1001: The type &apos;{0}&apos; is already defined ähnelt.
        /// </summary>
        internal static string D1001 {
            get {
                return ResourceManager.GetString("D1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1002: The function &apos;{0}&apos; is already defined ähnelt.
        /// </summary>
        internal static string D1002 {
            get {
                return ResourceManager.GetString("D1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1003: This unit contain more that one program ähnelt.
        /// </summary>
        internal static string D1003 {
            get {
                return ResourceManager.GetString("D1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1004: The variable &apos;{0}&apos; is already defined ähnelt.
        /// </summary>
        internal static string D1004 {
            get {
                return ResourceManager.GetString("D1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1005: The member &apos;{0}&apos; of the struct &apos;{1}&apos; is already defined ähnelt.
        /// </summary>
        internal static string D1005 {
            get {
                return ResourceManager.GetString("D1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1006: The lenght of the default value &apos;{0}&apos; is to large for the string ähnelt.
        /// </summary>
        internal static string D1006 {
            get {
                return ResourceManager.GetString("D1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1007: The function return variable &apos;{0}&apos; is already defined ähnelt.
        /// </summary>
        internal static string D1007 {
            get {
                return ResourceManager.GetString("D1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error D1008: The enumeration type &apos;{0}&apos; is already defined ähnelt.
        /// </summary>
        internal static string D1008 {
            get {
                return ResourceManager.GetString("D1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1001: The type of the symbol &apos;{0}&apos; is not compatible as array range ähnelt.
        /// </summary>
        internal static string G1001 {
            get {
                return ResourceManager.GetString("G1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1002: The default value &apos;{0}&apos; is not valid ähnelt.
        /// </summary>
        internal static string G1002 {
            get {
                return ResourceManager.GetString("G1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1004: The default value type does&apos;t correspond to the variable type ähnelt.
        /// </summary>
        internal static string G1004 {
            get {
                return ResourceManager.GetString("G1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1005: Undefined symbol &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string G1005 {
            get {
                return ResourceManager.GetString("G1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1006: The type of the symbol &apos;{0}&apos; is not compatible as array dimension ähnelt.
        /// </summary>
        internal static string G1006 {
            get {
                return ResourceManager.GetString("G1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1007: Wrong array range for &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string G1007 {
            get {
                return ResourceManager.GetString("G1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1008: Wrong array default initialization for &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string G1008 {
            get {
                return ResourceManager.GetString("G1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1009: The constant variable &apos;{0}&apos; must have a default value ähnelt.
        /// </summary>
        internal static string G1009 {
            get {
                return ResourceManager.GetString("G1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1010: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; is an output parameter and cannot be assigned to a constant ähnelt.
        /// </summary>
        internal static string G1010 {
            get {
                return ResourceManager.GetString("G1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1011: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; is an private parameter and cannot be assigned ähnelt.
        /// </summary>
        internal static string G1011 {
            get {
                return ResourceManager.GetString("G1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1012: The parameter &apos;{0}&apos; of the function &apos;{1}&apos; can not be initialised with default values in the FB ähnelt.
        /// </summary>
        internal static string G1012 {
            get {
                return ResourceManager.GetString("G1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1013: The variable &apos;{0}&apos; of type FB can not be instantiated in a constant section ähnelt.
        /// </summary>
        internal static string G1013 {
            get {
                return ResourceManager.GetString("G1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1013: The variable &apos;{0}&apos; of type FB can not be instantiated (Size = 0) ähnelt.
        /// </summary>
        internal static string G1014 {
            get {
                return ResourceManager.GetString("G1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error G1015: The data type &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string G1015 {
            get {
                return ResourceManager.GetString("G1015", resourceCulture);
            }
        }
    }
}
