//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Mod.Controller {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Mod.Controller.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller ähnelt.
        /// </summary>
        internal static string AutomaticControl {
            get {
                return ResourceManager.GetString("AutomaticControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fuzzy Controller ähnelt.
        /// </summary>
        internal static string FuzzyController {
            get {
                return ResourceManager.GetString("FuzzyController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fuzzy Controller
        ///
        ///A Fuzzy Controller for one or more signals. ähnelt.
        /// </summary>
        internal static string FuzzyControllerDescrp {
            get {
                return ResourceManager.GetString("FuzzyControllerDescrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The input port &apos;{0}&apos; of the element &apos;{1}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string InPortINotCon {
            get {
                return ResourceManager.GetString("InPortINotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; has one or more invalid fuzzy rules. ähnelt.
        /// </summary>
        internal static string InvalidRulesErr {
            get {
                return ResourceManager.GetString("InvalidRulesErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error L1001: Syntax error unexpected symbol found ähnelt.
        /// </summary>
        internal static string L1001 {
            get {
                return ResourceManager.GetString("L1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linguistic variable needs a name. ähnelt.
        /// </summary>
        internal static string LigNameErr {
            get {
                return ResourceManager.GetString("LigNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum 2 linguistic variables expected. ähnelt.
        /// </summary>
        internal static string Min2LinguisticVarErr {
            get {
                return ResourceManager.GetString("Min2LinguisticVarErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal maximum must be greater as the signal minimum. ähnelt.
        /// </summary>
        internal static string MinMaxError {
            get {
                return ResourceManager.GetString("MinMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linguistic variables are not definied. ähnelt.
        /// </summary>
        internal static string NoLingVarDef {
            get {
                return ResourceManager.GetString("NoLingVarDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linguistic variable name &apos;{0}&apos; is more that ones available. ähnelt.
        /// </summary>
        internal static string NoLingVarDuppErr {
            get {
                return ResourceManager.GetString("NoLingVarDuppErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No rules defined. ähnelt.
        /// </summary>
        internal static string NoRulesDefErr {
            get {
                return ResourceManager.GetString("NoRulesDefErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port &apos;{0}&apos; of the element &apos;{1}&apos; don&apos;t have signals. ähnelt.
        /// </summary>
        internal static string OutPortINoSigErr {
            get {
                return ResourceManager.GetString("OutPortINoSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port &apos;{0}&apos; of the element &apos;{1}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string OutPortINotCon {
            get {
                return ResourceManager.GetString("OutPortINotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error P1001: Syntax error unexpected symbol &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string P1001 {
            get {
                return ResourceManager.GetString("P1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PID Controller ähnelt.
        /// </summary>
        internal static string PIDController {
            get {
                return ResourceManager.GetString("PIDController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PID Controller
        ///
        ///A PID controller element. ähnelt.
        /// </summary>
        internal static string PIDControllerDescrp {
            get {
                return ResourceManager.GetString("PIDControllerDescrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The rules contain some errors. ähnelt.
        /// </summary>
        internal static string RulesErr {
            get {
                return ResourceManager.GetString("RulesErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A name for the signal is expected. ähnelt.
        /// </summary>
        internal static string SignalNameErr {
            get {
                return ResourceManager.GetString("SignalNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Three-Point Controller ähnelt.
        /// </summary>
        internal static string ThreeStepController {
            get {
                return ResourceManager.GetString("ThreeStepController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Three-Point Controller
        ///
        ///A Three-Point controller element. ähnelt.
        /// </summary>
        internal static string ThreeStepControllerDescrp {
            get {
                return ResourceManager.GetString("ThreeStepControllerDescrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Point Controller ähnelt.
        /// </summary>
        internal static string TwoLevelController {
            get {
                return ResourceManager.GetString("TwoLevelController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Point Controller
        ///
        ///A Two-Point controller element. ähnelt.
        /// </summary>
        internal static string TwoLevelControllerDscr {
            get {
                return ResourceManager.GetString("TwoLevelControllerDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : error C1001: Undefined linguistic variable ähnelt.
        /// </summary>
        internal static string UndefinedSymbol {
            get {
                return ResourceManager.GetString("UndefinedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The relation &quot;x1 &lt; x2 &lt; x3 &lt; x4&quot; must be satisfied. ähnelt.
        /// </summary>
        internal static string X1X2X3Err {
            get {
                return ResourceManager.GetString("X1X2X3Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A value of 0 is invalid. ähnelt.
        /// </summary>
        internal static string ZeroErr {
            get {
                return ResourceManager.GetString("ZeroErr", resourceCulture);
            }
        }
    }
}
