# Runtime
MeaProcess.runtime = "BEAGLEBONE";
MeaProcess.schemeFileLocation = "/opt/atesion/mea/data/schema.scm";
MeaProcess.systemConfiguration = { "", "" };

# Logging
MeaProcess.Logging.channel = "file:////opt/atesion/mea/data/mea.log?size=1024000&files=3";
MeaProcess.Logging.level   = "Trace";

# Scripting
MeaProcess.XmlRpc.on   = bool(true);
MeaProcess.XmlRcp.port = 5040;

# Deploy 
MeaProcess.Network.on   = bool(true)
MeaProcess.Network.port = 5000;

MeaProcess.SerialDevice.on       = bool(false);
MeaProcess.SerialDevice.device   = "/dev/ttyS0";
MeaProcess.SerialDevice.baudrate = 115200;






