//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Visual.Digital {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Visual.Digital.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the body of the button.
        /// </summary>
        internal static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label of the button.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of the button.
        /// </summary>
        internal static string ButtonState {
            get {
                return ResourceManager.GetString("ButtonState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of the button.
        /// </summary>
        internal static string ButtonStyle {
            get {
                return ResourceManager.GetString("ButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the button.
        /// </summary>
        internal static string ButtonType {
            get {
                return ResourceManager.GetString("ButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knob.
        /// </summary>
        internal static string Knob {
            get {
                return ResourceManager.GetString("Knob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the knob.
        /// </summary>
        internal static string KnobColor {
            get {
                return ResourceManager.GetString("KnobColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value of the knob.
        /// </summary>
        internal static string KnobCurValue {
            get {
                return ResourceManager.GetString("KnobCurValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset of the indicator from the kob border.
        /// </summary>
        internal static string KnobIndicatorBorderOffset {
            get {
                return ResourceManager.GetString("KnobIndicatorBorderOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the indicator.
        /// </summary>
        internal static string KnobIndicatorColor {
            get {
                return ResourceManager.GetString("KnobIndicatorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value of the knob.
        /// </summary>
        internal static string KnobMaxValue {
            get {
                return ResourceManager.GetString("KnobMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value of the knob.
        /// </summary>
        internal static string KnobMinValue {
            get {
                return ResourceManager.GetString("KnobMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the scale.
        /// </summary>
        internal static string KnobScaleColor {
            get {
                return ResourceManager.GetString("KnobScaleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step value of the knob.
        /// </summary>
        internal static string KnobStepValue {
            get {
                return ResourceManager.GetString("KnobStepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of the knob.
        /// </summary>
        internal static string KnobStyle {
            get {
                return ResourceManager.GetString("KnobStyle", resourceCulture);
            }
        }
    }
}
