//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Visual.XYChart {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Visual.XYChart.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the axis color. ähnelt.
        /// </summary>
        internal static string AxisColor {
            get {
                return ResourceManager.GetString("AxisColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors ähnelt.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The curve no. {0} don&apos;t have a Y signal assigned. ähnelt.
        /// </summary>
        internal static string CurveYSigAssgn {
            get {
                return ResourceManager.GetString("CurveYSigAssgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows the lines. ähnelt.
        /// </summary>
        internal static string DrawLine {
            get {
                return ResourceManager.GetString("DrawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows the points. ähnelt.
        /// </summary>
        internal static string DrawPoint {
            get {
                return ResourceManager.GetString("DrawPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow user to edit the chart properties ähnelt.
        /// </summary>
        internal static string Editable {
            get {
                return ResourceManager.GetString("Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grid ähnelt.
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the grid color. ähnelt.
        /// </summary>
        internal static string GridColor {
            get {
                return ResourceManager.GetString("GridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the grid line style. ähnelt.
        /// </summary>
        internal static string GridLineStyle {
            get {
                return ResourceManager.GetString("GridLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the grid X division. ähnelt.
        /// </summary>
        internal static string GridXDivision {
            get {
                return ResourceManager.GetString("GridXDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the grid Y division. ähnelt.
        /// </summary>
        internal static string GridYDivision {
            get {
                return ResourceManager.GetString("GridYDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the line color. ähnelt.
        /// </summary>
        internal static string LineColor {
            get {
                return ResourceManager.GetString("LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By logarithmic scale the minimum and maximum must be greater or equal as 1. ähnelt.
        /// </summary>
        internal static string LogRangeErr {
            get {
                return ResourceManager.GetString("LogRangeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of points in the chart. ähnelt.
        /// </summary>
        internal static string NoOfPoints {
            get {
                return ResourceManager.GetString("NoOfPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the point color. ähnelt.
        /// </summary>
        internal static string PointColor {
            get {
                return ResourceManager.GetString("PointColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference curves ähnelt.
        /// </summary>
        internal static string ReferenceCurves {
            get {
                return ResourceManager.GetString("ReferenceCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the selected reference curve(s)? ähnelt.
        /// </summary>
        internal static string RemoveRefCurve {
            get {
                return ResourceManager.GetString("RemoveRefCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the control panel. ähnelt.
        /// </summary>
        internal static string ShowControlPanel {
            get {
                return ResourceManager.GetString("ShowControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define if this diagram is a spectrum diagram. ähnelt.
        /// </summary>
        internal static string SpectrumDiagram {
            get {
                return ResourceManager.GetString("SpectrumDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        internal static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the X-axis devision. ähnelt.
        /// </summary>
        internal static string XAxisDevision {
            get {
                return ResourceManager.GetString("XAxisDevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the X-axis precision. ähnelt.
        /// </summary>
        internal static string XAxisPrecision {
            get {
                return ResourceManager.GetString("XAxisPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The X axis logarithmic. ähnelt.
        /// </summary>
        internal static string XLog {
            get {
                return ResourceManager.GetString("XLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the X-axis maximum. ähnelt.
        /// </summary>
        internal static string XMaximum {
            get {
                return ResourceManager.GetString("XMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the X-axis minimum. ähnelt.
        /// </summary>
        internal static string XMinimum {
            get {
                return ResourceManager.GetString("XMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The X maximum must be greather as minimum ähnelt.
        /// </summary>
        internal static string XMinMaxErr {
            get {
                return ResourceManager.GetString("XMinMaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the Y-axis devision. ähnelt.
        /// </summary>
        internal static string YAxisDevision {
            get {
                return ResourceManager.GetString("YAxisDevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the Y-axis precision. ähnelt.
        /// </summary>
        internal static string YAxisPrecision {
            get {
                return ResourceManager.GetString("YAxisPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Y axis logatithmic ähnelt.
        /// </summary>
        internal static string YLog {
            get {
                return ResourceManager.GetString("YLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the Y-axis maximum. ähnelt.
        /// </summary>
        internal static string YMaximum {
            get {
                return ResourceManager.GetString("YMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the Y-axis minimum. ähnelt.
        /// </summary>
        internal static string YMinimum {
            get {
                return ResourceManager.GetString("YMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Y maximum must be greather as minimum. ähnelt.
        /// </summary>
        internal static string YMinMaxErr {
            get {
                return ResourceManager.GetString("YMinMaxErr", resourceCulture);
            }
        }
    }
}
