//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Drv.CANdb {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Drv.CANdb.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal bit count expected. ähnelt.
        /// </summary>
        internal static string BitCountErr {
            get {
                return ResourceManager.GetString("BitCountErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message &apos;Byte count&apos; expected. ähnelt.
        /// </summary>
        internal static string ByteCoutErr {
            get {
                return ResourceManager.GetString("ByteCoutErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal byte order and data sign expected. ähnelt.
        /// </summary>
        internal static string ByteOrderErr {
            get {
                return ResourceManager.GetString("ByteOrderErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal factor and offset expected. ähnelt.
        /// </summary>
        internal static string FactorOffsetErr {
            get {
                return ResourceManager.GetString("FactorOffsetErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0} could not be opened. ähnelt.
        /// </summary>
        internal static string FileOpenErr {
            get {
                return ResourceManager.GetString("FileOpenErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode depended signal must have a mode value. ähnelt.
        /// </summary>
        internal static string ModeDepErr {
            get {
                return ResourceManager.GetString("ModeDepErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message definition is incorrect. ähnelt.
        /// </summary>
        internal static string MsgDefErr {
            get {
                return ResourceManager.GetString("MsgDefErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message ID expected. ähnelt.
        /// </summary>
        internal static string MsgIDErr {
            get {
                return ResourceManager.GetString("MsgIDErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal definition is incorrect. ähnelt.
        /// </summary>
        internal static string SigDefErr {
            get {
                return ResourceManager.GetString("SigDefErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal [min|max] expected. ähnelt.
        /// </summary>
        internal static string SignalMinMaxErr {
            get {
                return ResourceManager.GetString("SignalMinMaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A signal without a message is not allowed. ähnelt.
        /// </summary>
        internal static string SigWithoutMsgErr {
            get {
                return ResourceManager.GetString("SigWithoutMsgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal start bit expected. ähnelt.
        /// </summary>
        internal static string StartBitErr {
            get {
                return ResourceManager.GetString("StartBitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong value type definition. ähnelt.
        /// </summary>
        internal static string WrongValType {
            get {
                return ResourceManager.GetString("WrongValType", resourceCulture);
            }
        }
    }
}
