//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Visual.Digital {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Visual.Digital.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the axis division. ähnelt.
        /// </summary>
        internal static string AxisDivision {
            get {
                return ResourceManager.GetString("AxisDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the number precision of the axis. ähnelt.
        /// </summary>
        internal static string AxisPrecision {
            get {
                return ResourceManager.GetString("AxisPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the bar color. ähnelt.
        /// </summary>
        internal static string BarColor {
            get {
                return ResourceManager.GetString("BarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button ähnelt.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of the body of the button ähnelt.
        /// </summary>
        internal static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label of the button ähnelt.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State of the button ähnelt.
        /// </summary>
        internal static string ButtonState {
            get {
                return ResourceManager.GetString("ButtonState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style of the button ähnelt.
        /// </summary>
        internal static string ButtonStyle {
            get {
                return ResourceManager.GetString("ButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type of the button ähnelt.
        /// </summary>
        internal static string ButtonType {
            get {
                return ResourceManager.GetString("ButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background color of the LED array ähnelt.
        /// </summary>
        internal static string ColorBackground {
            get {
                return ResourceManager.GetString("ColorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of inactive LED segments. ähnelt.
        /// </summary>
        internal static string ColorDark {
            get {
                return ResourceManager.GetString("ColorDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of active LED segments. ähnelt.
        /// </summary>
        internal static string ColorLight {
            get {
                return ResourceManager.GetString("ColorLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the Combo Box items. ähnelt.
        /// </summary>
        internal static string ComboItems {
            get {
                return ResourceManager.GetString("ComboItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of seven-segment elements in this array ähnelt.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Segment width ähnelt.
        /// </summary>
        internal static string ElementWidth {
            get {
                return ResourceManager.GetString("ElementWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hides the signal name. ähnelt.
        /// </summary>
        internal static string HideSignalName {
            get {
                return ResourceManager.GetString("HideSignalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hides the signal unit. ähnelt.
        /// </summary>
        internal static string HideSignalUnit {
            get {
                return ResourceManager.GetString("HideSignalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The width of the label. ähnelt.
        /// </summary>
        internal static string LabelWidth {
            get {
                return ResourceManager.GetString("LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LED view ähnelt.
        /// </summary>
        internal static string LEDView {
            get {
                return ResourceManager.GetString("LEDView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the view Limits. ähnelt.
        /// </summary>
        internal static string Limits {
            get {
                return ResourceManager.GetString("Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limits ähnelt.
        /// </summary>
        internal static string LimitsText {
            get {
                return ResourceManager.GetString("LimitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum value. ähnelt.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The minimum value. ähnelt.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of samples into the view. ähnelt.
        /// </summary>
        internal static string NoOfSamples {
            get {
                return ResourceManager.GetString("NoOfSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type of the number. ähnelt.
        /// </summary>
        internal static string NumberType {
            get {
                return ResourceManager.GetString("NumberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off switch label. ähnelt.
        /// </summary>
        internal static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On switch label. ähnelt.
        /// </summary>
        internal static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the view orientation. ähnelt.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of position after decimal point. ähnelt.
        /// </summary>
        internal static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the Radio Buttons. ähnelt.
        /// </summary>
        internal static string RBItems {
            get {
                return ResourceManager.GetString("RBItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the axis ähnelt.
        /// </summary>
        internal static string ShowAxis {
            get {
                return ResourceManager.GetString("ShowAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the signal column width. ähnelt.
        /// </summary>
        internal static string SignalWidth {
            get {
                return ResourceManager.GetString("SignalWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the unit column width. ähnelt.
        /// </summary>
        internal static string UnitWidth {
            get {
                return ResourceManager.GetString("UnitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper limit must be greater as the lower limit. ähnelt.
        /// </summary>
        internal static string UpperLowerErr {
            get {
                return ResourceManager.GetString("UpperLowerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value. ähnelt.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The backgroundcolor of the value. ähnelt.
        /// </summary>
        internal static string ValueBoxBackColor {
            get {
                return ResourceManager.GetString("ValueBoxBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The foregroundcolor of the value. ähnelt.
        /// </summary>
        internal static string ValueBoxForeColor {
            get {
                return ResourceManager.GetString("ValueBoxForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the value column width. ähnelt.
        /// </summary>
        internal static string ValueWidthCol {
            get {
                return ResourceManager.GetString("ValueWidthCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        internal static string View1 {
            get {
                return ResourceManager.GetString("View1", resourceCulture);
            }
        }
    }
}
