//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Mod.Clock {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Mod.Clock.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clock ähnelt.
        /// </summary>
        internal static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clock
        ///
        ///Acquire the current time and date. ähnelt.
        /// </summary>
        internal static string ClockPsDescription {
            get {
                return ResourceManager.GetString("ClockPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data output port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string DataOutPortConError {
            get {
                return ResourceManager.GetString("DataOutPortConError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data output port of the element &apos;{0}&apos; don&apos;t have signals defined. ähnelt.
        /// </summary>
        internal static string DataOutPortSigError {
            get {
                return ResourceManager.GetString("DataOutPortSigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only a even frequency is supported ähnelt.
        /// </summary>
        internal static string EvenFreqErr {
            get {
                return ResourceManager.GetString("EvenFreqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hour ähnelt.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Millisecond ähnelt.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minute ähnelt.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A periode of 0 is not defined. ähnelt.
        /// </summary>
        internal static string PeriodeErr {
            get {
                return ResourceManager.GetString("PeriodeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Second ähnelt.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal must have a name. ähnelt.
        /// </summary>
        internal static string SignalNameErr {
            get {
                return ResourceManager.GetString("SignalNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal must have a name. ähnelt.
        /// </summary>
        internal static string SigNameErr {
            get {
                return ResourceManager.GetString("SigNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopwatch ähnelt.
        /// </summary>
        internal static string StopWatch {
            get {
                return ResourceManager.GetString("StopWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopwatch
        ///
        ///Stopwatch with start/stop trigger and reset input. ähnelt.
        /// </summary>
        internal static string StopWatchPsDescription {
            get {
                return ResourceManager.GetString("StopWatchPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tact ähnelt.
        /// </summary>
        internal static string Tact {
            get {
                return ResourceManager.GetString("Tact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tact
        ///
        ///Generate tact signals. ähnelt.
        /// </summary>
        internal static string TactPSDescription {
            get {
                return ResourceManager.GetString("TactPSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer ähnelt.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer
        ///
        ///Generate time event signals ähnelt.
        /// </summary>
        internal static string TimerPsDescription {
            get {
                return ResourceManager.GetString("TimerPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The timer resolution is 10ms. Only multiplier of 10 is supported as interval. ähnelt.
        /// </summary>
        internal static string TimerRes10Err {
            get {
                return ResourceManager.GetString("TimerRes10Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; needs a trigger signal to execute the program. ähnelt.
        /// </summary>
        internal static string TriggerForProgErr {
            get {
                return ResourceManager.GetString("TriggerForProgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger input port of the element &apos;{0}&apos; expect minimum one input signal for this trigger type. ähnelt.
        /// </summary>
        internal static string TriggerOneSigErr {
            get {
                return ResourceManager.GetString("TriggerOneSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger port with start/stop trigger of the element &apos;{0}&apos; need two signal. ähnelt.
        /// </summary>
        internal static string TriggerPortNeed2SigErr {
            get {
                return ResourceManager.GetString("TriggerPortNeed2SigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger input port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string TriggerPortNotConErr {
            get {
                return ResourceManager.GetString("TriggerPortNotConErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger port of the element &apos;{0}&apos; don&apos;t have a signal. ähnelt.
        /// </summary>
        internal static string TriggerPortSigError {
            get {
                return ResourceManager.GetString("TriggerPortSigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A trigger signal is expected. ähnelt.
        /// </summary>
        internal static string TriggerSigExpectedErr {
            get {
                return ResourceManager.GetString("TriggerSigExpectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A time period for pre trigger and post trigger is expected. ähnelt.
        /// </summary>
        internal static string TriggerTimePerErr {
            get {
                return ResourceManager.GetString("TriggerTimePerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger input port of the element &apos;{0}&apos; expect minimum two input signals for this trigger type. ähnelt.
        /// </summary>
        internal static string TriggerTwoSigErr {
            get {
                return ResourceManager.GetString("TriggerTwoSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A generation rate of 0 is not supported. ähnelt.
        /// </summary>
        internal static string ZeroGenRateErr {
            get {
                return ResourceManager.GetString("ZeroGenRateErr", resourceCulture);
            }
        }
    }
}
