//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Mod.Storage {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Mod.Storage.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property for the &apos;command&apos; of the element &apos;&apos; is not defined. ähnelt.
        /// </summary>
        internal static string CommandPropNotDef {
            get {
                return ResourceManager.GetString("CommandPropNotDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A data file for runtime is expected. ähnelt.
        /// </summary>
        internal static string DataFileExpected {
            get {
                return ResourceManager.GetString("DataFileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A data file for the element &apos;{0} &apos; is expected. ähnelt.
        /// </summary>
        internal static string DataFileForPsExpected {
            get {
                return ResourceManager.GetString("DataFileForPsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data input port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string DataInPortNotConnectedErr {
            get {
                return ResourceManager.GetString("DataInPortNotConnectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data output port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string DataOutPortConError {
            get {
                return ResourceManager.GetString("DataOutPortConError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data output port of the element &apos;{0}&apos; don&apos;t have signals defined. ähnelt.
        /// </summary>
        internal static string DataOutPortSigError {
            get {
                return ResourceManager.GetString("DataOutPortSigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file or property expected. ähnelt.
        /// </summary>
        internal static string DataStorageFileErr {
            get {
                return ResourceManager.GetString("DataStorageFileErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The measurement comment for the element &apos;{0}&apos; is not defined. ähnelt.
        /// </summary>
        internal static string MeaCommentNotDef {
            get {
                return ResourceManager.GetString("MeaCommentNotDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property is not available. ähnelt.
        /// </summary>
        internal static string PropNotAvail {
            get {
                return ResourceManager.GetString("PropNotAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Data ähnelt.
        /// </summary>
        internal static string ReadData {
            get {
                return ResourceManager.GetString("ReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Data
        ///
        ///Reads measurement data from a file. ähnelt.
        /// </summary>
        internal static string ReadDataPsDescription {
            get {
                return ResourceManager.GetString("ReadDataPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element {0} don&apos;t accespt signals of object type. ähnelt.
        /// </summary>
        internal static string SigObjetErr {
            get {
                return ResourceManager.GetString("SigObjetErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The storage file for the element &apos;{0}&apos; is not defined. ähnelt.
        /// </summary>
        internal static string StorageFileNotDef {
            get {
                return ResourceManager.GetString("StorageFileNotDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger port with start/stop trigger of the element &apos;{0}&apos; need two signal. ähnelt.
        /// </summary>
        internal static string TriggerPortNeed2SigErr {
            get {
                return ResourceManager.GetString("TriggerPortNeed2SigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger port of the element &apos;{0}&apos; don&apos;t have a signal. ähnelt.
        /// </summary>
        internal static string TriggerPortSigError {
            get {
                return ResourceManager.GetString("TriggerPortSigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write Data ähnelt.
        /// </summary>
        internal static string WriteData {
            get {
                return ResourceManager.GetString("WriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write Data
        ///
        ///Write the measurement data into a file. ähnelt.
        /// </summary>
        internal static string WriteDataPsDescription {
            get {
                return ResourceManager.GetString("WriteDataPsDescription", resourceCulture);
            }
        }
    }
}
