//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Visual.Analog {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Visual.Analog.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value where the pointer will point to. ähnelt.
        /// </summary>
        internal static string AQValue {
            get {
                return ResourceManager.GetString("AQValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arc ähnelt.
        /// </summary>
        internal static string Arc {
            get {
                return ResourceManager.GetString("Arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The color of the base arc. ähnelt.
        /// </summary>
        internal static string BaseArcColor {
            get {
                return ResourceManager.GetString("BaseArcColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The radius of the base arc. ähnelt.
        /// </summary>
        internal static string BaseArcRadius {
            get {
                return ResourceManager.GetString("BaseArcRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The start angle of the base arc. ähnelt.
        /// </summary>
        internal static string BaseArcStart {
            get {
                return ResourceManager.GetString("BaseArcStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sweep angle of the base arc. ähnelt.
        /// </summary>
        internal static string BaseArcSweep {
            get {
                return ResourceManager.GetString("BaseArcSweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The width of the base arc. ähnelt.
        /// </summary>
        internal static string BaseArcWidth {
            get {
                return ResourceManager.GetString("BaseArcWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button ähnelt.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of the body of the button ähnelt.
        /// </summary>
        internal static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label of the button ähnelt.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State of the button ähnelt.
        /// </summary>
        internal static string ButtonState {
            get {
                return ResourceManager.GetString("ButtonState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style of the button ähnelt.
        /// </summary>
        internal static string ButtonStyle {
            get {
                return ResourceManager.GetString("ButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type of the button ähnelt.
        /// </summary>
        internal static string ButtonType {
            get {
                return ResourceManager.GetString("ButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caption ähnelt.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the captions text. ähnelt.
        /// </summary>
        internal static string CaptionDefinition {
            get {
                return ResourceManager.GetString("CaptionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The center of the gauge (in the control&apos;s client area). ähnelt.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background color of the dial ähnelt.
        /// </summary>
        internal static string DialColor {
            get {
                return ResourceManager.GetString("DialColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Define the display mode. ähnelt.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gauge ähnelt.
        /// </summary>
        internal static string Gauge {
            get {
                return ResourceManager.GetString("Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string GaugeValue {
            get {
                return ResourceManager.GetString("GaugeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knob ähnelt.
        /// </summary>
        internal static string Knob {
            get {
                return ResourceManager.GetString("Knob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of the knob ähnelt.
        /// </summary>
        internal static string KnobColor {
            get {
                return ResourceManager.GetString("KnobColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current value of the knob ähnelt.
        /// </summary>
        internal static string KnobCurValue {
            get {
                return ResourceManager.GetString("KnobCurValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset of the indicator from the kob border ähnelt.
        /// </summary>
        internal static string KnobIndicatorBorderOffset {
            get {
                return ResourceManager.GetString("KnobIndicatorBorderOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of the indicator ähnelt.
        /// </summary>
        internal static string KnobIndicatorColor {
            get {
                return ResourceManager.GetString("KnobIndicatorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum value of the knob ähnelt.
        /// </summary>
        internal static string KnobMaxValue {
            get {
                return ResourceManager.GetString("KnobMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum value of the knob ähnelt.
        /// </summary>
        internal static string KnobMinValue {
            get {
                return ResourceManager.GetString("KnobMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of the scale ähnelt.
        /// </summary>
        internal static string KnobScaleColor {
            get {
                return ResourceManager.GetString("KnobScaleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step value of the knob ähnelt.
        /// </summary>
        internal static string KnobStepValue {
            get {
                return ResourceManager.GetString("KnobStepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style of the knob ähnelt.
        /// </summary>
        internal static string KnobStyle {
            get {
                return ResourceManager.GetString("KnobStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the large tic frequency. ähnelt.
        /// </summary>
        internal static string LargeTicFreq {
            get {
                return ResourceManager.GetString("LargeTicFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum value on the scale. ähnelt.
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mininum value on the scale. ähnelt.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Needle ähnelt.
        /// </summary>
        internal static string Needle {
            get {
                return ResourceManager.GetString("Needle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first color of the needle. ähnelt.
        /// </summary>
        internal static string NeedleColor1 {
            get {
                return ResourceManager.GetString("NeedleColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The second color of the needle. ähnelt.
        /// </summary>
        internal static string NeedleColor2 {
            get {
                return ResourceManager.GetString("NeedleColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The radius of the needle. ähnelt.
        /// </summary>
        internal static string NeedleRadius {
            get {
                return ResourceManager.GetString("NeedleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type of the needle, currently only type 0 and 1 are supported. Type 0 looks nicers but if you experience performance problems you might consider using type 1. ähnelt.
        /// </summary>
        internal static string NeedleType {
            get {
                return ResourceManager.GetString("NeedleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The width of the needle. ähnelt.
        /// </summary>
        internal static string NeedleWidth {
            get {
                return ResourceManager.GetString("NeedleWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of divisions in the dial scale. ähnelt.
        /// </summary>
        internal static string NoOfDivisions {
            get {
                return ResourceManager.GetString("NoOfDivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of sub divisions in the scale per main division. ähnelt.
        /// </summary>
        internal static string NoOfSubDivisions {
            get {
                return ResourceManager.GetString("NoOfSubDivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A positiv number is expected ähnelt.
        /// </summary>
        internal static string PosNoErr {
            get {
                return ResourceManager.GetString("PosNoErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range ähnelt.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the gauge ranges. ähnelt.
        /// </summary>
        internal static string RangeDefinition {
            get {
                return ResourceManager.GetString("RangeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the range maximum in Fahreinheit. ähnelt.
        /// </summary>
        internal static string RangeMax {
            get {
                return ResourceManager.GetString("RangeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the range minimum in Fahreinheit. ähnelt.
        /// </summary>
        internal static string RangeMin {
            get {
                return ResourceManager.GetString("RangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale Lines ähnelt.
        /// </summary>
        internal static string ScaleLines {
            get {
                return ResourceManager.GetString("ScaleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The color of the inter scale lines which are the middle scale lines for an uneven number of minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesInterColor {
            get {
                return ResourceManager.GetString("ScaleLinesInterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The inner radius of the inter scale lines which are the middle scale lines for an uneven number of minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesInterInnerRadius {
            get {
                return ResourceManager.GetString("ScaleLinesInterInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The outer radius of the inter scale lines which are the middle scale lines for an uneven number of minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesInterOuterRadius {
            get {
                return ResourceManager.GetString("ScaleLinesInterOuterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The width of the inter scale lines which are the middle scale lines for an uneven number of minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesInterWidth {
            get {
                return ResourceManager.GetString("ScaleLinesInterWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The color of the major scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMajorColor {
            get {
                return ResourceManager.GetString("ScaleLinesMajorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The inner radius of the major scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMajorInnerRadius {
            get {
                return ResourceManager.GetString("ScaleLinesMajorInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The outer radius of the major scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMajorOuterRadius {
            get {
                return ResourceManager.GetString("ScaleLinesMajorOuterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The step value of the major scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMajorStepValue {
            get {
                return ResourceManager.GetString("ScaleLinesMajorStepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The width of the major scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMajorWidth {
            get {
                return ResourceManager.GetString("ScaleLinesMajorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The color of the minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMinorColor {
            get {
                return ResourceManager.GetString("ScaleLinesMinorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The inner radius of the minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMinorInnerRadius {
            get {
                return ResourceManager.GetString("ScaleLinesMinorInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMinorNumOf {
            get {
                return ResourceManager.GetString("ScaleLinesMinorNumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The outer radius of the minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMinorOuterRadius {
            get {
                return ResourceManager.GetString("ScaleLinesMinorOuterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The width of the minor scale lines. ähnelt.
        /// </summary>
        internal static string ScaleLinesMinorWidth {
            get {
                return ResourceManager.GetString("ScaleLinesMinorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale Numbers ähnelt.
        /// </summary>
        internal static string ScaleNumbers {
            get {
                return ResourceManager.GetString("ScaleNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The color of the scale numbers. ähnelt.
        /// </summary>
        internal static string ScaleNumbersColor {
            get {
                return ResourceManager.GetString("ScaleNumbersColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The format of the scale numbers. ähnelt.
        /// </summary>
        internal static string ScaleNumbersFormat {
            get {
                return ResourceManager.GetString("ScaleNumbersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The radius of the scale numbers. ähnelt.
        /// </summary>
        internal static string ScaleNumbersRadius {
            get {
                return ResourceManager.GetString("ScaleNumbersRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The angle relative to the tangent of the base arc at a scale line that is used to rotate numbers. Set to 0 for no rotation or e.g. set to 90. ähnelt.
        /// </summary>
        internal static string ScaleNumbersRotation {
            get {
                return ResourceManager.GetString("ScaleNumbersRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of the scale line to start writing numbers next to. ähnelt.
        /// </summary>
        internal static string ScaleNumbersStartScaleLine {
            get {
                return ResourceManager.GetString("ScaleNumbersStartScaleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of scale line steps for writing numbers. ähnelt.
        /// </summary>
        internal static string ScaleNumbersStepScaleLines {
            get {
                return ResourceManager.GetString("ScaleNumbersStepScaleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the small tic frequency. ähnelt.
        /// </summary>
        internal static string SmallTicFreq {
            get {
                return ResourceManager.GetString("SmallTicFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thermometer ähnelt.
        /// </summary>
        internal static string Thermometer {
            get {
                return ResourceManager.GetString("Thermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define the current value. ähnelt.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        internal static string View1 {
            get {
                return ResourceManager.GetString("View1", resourceCulture);
            }
        }
    }
}
