//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Scheme.Sdk.Ui {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Scheme.Sdk.Ui.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bar view ähnelt.
        /// </summary>
        internal static string BarView {
            get {
                return ResourceManager.GetString("BarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bar view
        ///
        ///Display a signal into a bar view. ähnelt.
        /// </summary>
        internal static string BarViewPsDescription {
            get {
                return ResourceManager.GetString("BarViewPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button ähnelt.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button
        ///
        ///Generate a button press signal. ähnelt.
        /// </summary>
        internal static string ButtonPsDescription {
            get {
                return ResourceManager.GetString("ButtonPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Box ähnelt.
        /// </summary>
        internal static string CheckBoxPS {
            get {
                return ResourceManager.GetString("CheckBoxPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Box
        ///
        ///Generate a signal from the Check Box control. ähnelt.
        /// </summary>
        internal static string CheckBoxPsDescription {
            get {
                return ResourceManager.GetString("CheckBoxPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Combo Box
        ///
        ///Generate a signal from a Combo Box selection. ähnelt.
        /// </summary>
        internal static string ComboBoxPsDescription {
            get {
                return ResourceManager.GetString("ComboBoxPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control ähnelt.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Meter 1 ähnelt.
        /// </summary>
        internal static string DigitalMeter1 {
            get {
                return ResourceManager.GetString("DigitalMeter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Meter 1
        ///
        ///Visualise the signal into a Digital Meter with small digits. ähnelt.
        /// </summary>
        internal static string DigitalMeter1PsDescription {
            get {
                return ResourceManager.GetString("DigitalMeter1PsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Meter 2 ähnelt.
        /// </summary>
        internal static string DigitalMeter2 {
            get {
                return ResourceManager.GetString("DigitalMeter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Meter 2
        ///
        ///Visualise the signal into a Digital Meter with big digits display. ähnelt.
        /// </summary>
        internal static string DigitalMeter2PsDescription {
            get {
                return ResourceManager.GetString("DigitalMeter2PsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Meter 3 ähnelt.
        /// </summary>
        internal static string DigitalMeter3 {
            get {
                return ResourceManager.GetString("DigitalMeter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Meter 3
        ///
        ///Visualise the signal  into a Digital Meter with 7 segment display. ähnelt.
        /// </summary>
        internal static string DigitalMeter7PsDescription {
            get {
                return ResourceManager.GetString("DigitalMeter7PsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal Display ähnelt.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Display ähnelt.
        /// </summary>
        internal static string DisplayBlock {
            get {
                return ResourceManager.GetString("DisplayBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gauge ähnelt.
        /// </summary>
        internal static string Gauge {
            get {
                return ResourceManager.GetString("Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gauge
        ///
        ///Signals visualisation into a Gauge. ähnelt.
        /// </summary>
        internal static string GaugePsDescription {
            get {
                return ResourceManager.GetString("GaugePsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knob ähnelt.
        /// </summary>
        internal static string Knob {
            get {
                return ResourceManager.GetString("Knob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knob
        ///
        ///Generate a signal from a knob. ähnelt.
        /// </summary>
        internal static string KnobPsDescription {
            get {
                return ResourceManager.GetString("KnobPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LED
        ///
        ///Show the signal status into a LED. ähnelt.
        /// </summary>
        internal static string LEDPsDescription {
            get {
                return ResourceManager.GetString("LEDPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List view ähnelt.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List view
        ///
        ///Visualise signals into a list. ähnelt.
        /// </summary>
        internal static string ListViewPsDescription {
            get {
                return ResourceManager.GetString("ListViewPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manometer
        ///
        ///Visualise the signal into a Manometer. ähnelt.
        /// </summary>
        internal static string ManometerPsDescription {
            get {
                return ResourceManager.GetString("ManometerPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numeric Input ähnelt.
        /// </summary>
        internal static string NumericInput {
            get {
                return ResourceManager.GetString("NumericInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numeric Input
        ///
        ///Generate a signal from a numeric input. ähnelt.
        /// </summary>
        internal static string NumericInputPsDescription {
            get {
                return ResourceManager.GetString("NumericInputPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oscilloscope ähnelt.
        /// </summary>
        internal static string Oscilloscope {
            get {
                return ResourceManager.GetString("Oscilloscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oscilloscope
        ///
        ///Visualise the signal into a oscilloscope. ähnelt.
        /// </summary>
        internal static string OscilloscopePsDescription {
            get {
                return ResourceManager.GetString("OscilloscopePsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; expect minimum one input signal. ähnelt.
        /// </summary>
        internal static string OsciSigErr {
            get {
                return ResourceManager.GetString("OsciSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polar Chart ähnelt.
        /// </summary>
        internal static string PolarChart {
            get {
                return ResourceManager.GetString("PolarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polar Chart
        ///
        ///Visualise signals into a polar chart. ähnelt.
        /// </summary>
        internal static string PolarChartPsDescription {
            get {
                return ResourceManager.GetString("PolarChartPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string PropertiesMenu {
            get {
                return ResourceManager.GetString("PropertiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radio Buttons ähnelt.
        /// </summary>
        internal static string RadioButtons {
            get {
                return ResourceManager.GetString("RadioButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radio Buttons
        ///
        ///Generate a signal from Radion Buttons values. ähnelt.
        /// </summary>
        internal static string RadionButtonsPsDescription {
            get {
                return ResourceManager.GetString("RadionButtonsPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove the selected reference curve(s)? ähnelt.
        /// </summary>
        internal static string RemoveRefCurve {
            get {
                return ResourceManager.GetString("RemoveRefCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime Engine... ähnelt.
        /// </summary>
        internal static string RunTimeEngineMenu {
            get {
                return ResourceManager.GetString("RunTimeEngineMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the run time engine (F6). ähnelt.
        /// </summary>
        internal static string RunTimeEngineText {
            get {
                return ResourceManager.GetString("RunTimeEngineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime Options... ähnelt.
        /// </summary>
        internal static string RuntimeOptionsMenu {
            get {
                return ResourceManager.GetString("RuntimeOptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the runtime option dialog . ähnelt.
        /// </summary>
        internal static string RuntimeOptionsText {
            get {
                return ResourceManager.GetString("RuntimeOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slider ähnelt.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slider
        ///
        ///Generate a signal from a slider. ähnelt.
        /// </summary>
        internal static string SliderPsDescription {
            get {
                return ResourceManager.GetString("SliderPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The mapped signals must have the same source and sample rate. ähnelt.
        /// </summary>
        internal static string SrcRateErr {
            get {
                return ResourceManager.GetString("SrcRateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch ähnelt.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch
        ///
        ///Generate a signal from a two state switch. ähnelt.
        /// </summary>
        internal static string SwitchPsDescription {
            get {
                return ResourceManager.GetString("SwitchPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table View ähnelt.
        /// </summary>
        internal static string TableView {
            get {
                return ResourceManager.GetString("TableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table View
        ///
        ///Show the signals into a table. ähnelt.
        /// </summary>
        internal static string TableViewPsDescription {
            get {
                return ResourceManager.GetString("TableViewPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tachometer
        ///
        ///Visualise the signals in tachometer. ähnelt.
        /// </summary>
        internal static string TachometerPsDescription {
            get {
                return ResourceManager.GetString("TachometerPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thermometer
        ///
        ///Visualise the signals in tachometer. ähnelt.
        /// </summary>
        internal static string ThermometerPsDescription {
            get {
                return ResourceManager.GetString("ThermometerPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; expect two input signals. ähnelt.
        /// </summary>
        internal static string TwoSigErr {
            get {
                return ResourceManager.GetString("TwoSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y/t Chart ähnelt.
        /// </summary>
        internal static string WaveChart {
            get {
                return ResourceManager.GetString("WaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y/t Chart
        ///
        ///Visualise the signals in a wave chart (Y/t). ähnelt.
        /// </summary>
        internal static string WaveChartPsDescription {
            get {
                return ResourceManager.GetString("WaveChartPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        /// </summary>
        internal static string WinRuntime {
            get {
                return ResourceManager.GetString("WinRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X/Y Chart ähnelt.
        /// </summary>
        internal static string XYChart {
            get {
                return ResourceManager.GetString("XYChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X/Y Chart
        ///
        ///Visualise signals into a X/Y chart. ähnelt.
        /// </summary>
        internal static string XYChartPsDescription {
            get {
                return ResourceManager.GetString("XYChartPsDescription", resourceCulture);
            }
        }
    }
}
