//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Mod.OBD2 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Mod.OBD2.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auxiliary Input Status ähnelt.
        /// </summary>
        internal static string AuxInStatus {
            get {
                return ResourceManager.GetString("AuxInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibration identifications ähnelt.
        /// </summary>
        internal static string CalId {
            get {
                return ResourceManager.GetString("CalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibration verification number ähnelt.
        /// </summary>
        internal static string CalVerNo {
            get {
                return ResourceManager.GetString("CalVerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commanded Secondary Air Status ähnelt.
        /// </summary>
        internal static string CmdSecondaryAirStatus {
            get {
                return ResourceManager.GetString("CmdSecondaryAirStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU names ähnelt.
        /// </summary>
        internal static string ECUnames {
            get {
                return ResourceManager.GetString("ECUnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fuel System Status ähnelt.
        /// </summary>
        internal static string FuelSystemStatus {
            get {
                return ResourceManager.GetString("FuelSystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fuel type ähnelt.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OBD2 Input
        ///
        ///Acquire measurement data from OBD2. ähnelt.
        /// </summary>
        internal static string InputPSDescription {
            get {
                return ResourceManager.GetString("InputPSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of Oxygen Sensors $13 ähnelt.
        /// </summary>
        internal static string LocOxygen13 {
            get {
                return ResourceManager.GetString("LocOxygen13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of Oxygen Sensors $1D ähnelt.
        /// </summary>
        internal static string LocOxygen1D {
            get {
                return ResourceManager.GetString("LocOxygen1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor Status this Driving Cycle ähnelt.
        /// </summary>
        internal static string MonStatusDrivingCyc {
            get {
                return ResourceManager.GetString("MonStatusDrivingCyc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OBD2 DTC View ähnelt.
        /// </summary>
        internal static string OBD2DTCView {
            get {
                return ResourceManager.GetString("OBD2DTCView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OBD2 Input ähnelt.
        /// </summary>
        internal static string OBD2Input {
            get {
                return ResourceManager.GetString("OBD2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OBD2 Status View ähnelt.
        /// </summary>
        internal static string OBD2StatusView {
            get {
                return ResourceManager.GetString("OBD2StatusView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port &apos;{0}&apos; of the element &apos;{1}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string OutPortINotCon {
            get {
                return ResourceManager.GetString("OutPortINotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output ports of the element &apos;{0}&apos; don&apos;t have signals. ähnelt.
        /// </summary>
        internal static string OutPortsNoSig {
            get {
                return ResourceManager.GetString("OutPortsNoSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output ports of the element &apos;{0}&apos; are not connected. ähnelt.
        /// </summary>
        internal static string OutPortsNotCon {
            get {
                return ResourceManager.GetString("OutPortsNotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string PropertyMenu {
            get {
                return ResourceManager.GetString("PropertyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property &apos;{0}&apos; for the element &apos;{1}&apos; is not available. ähnelt.
        /// </summary>
        internal static string PropNotAvailErr {
            get {
                return ResourceManager.GetString("PropNotAvailErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property &apos;{0}&apos; for the element &apos;{1}&apos; has a wrong data type. ähnelt.
        /// </summary>
        internal static string PropWrongTypeErr {
            get {
                return ResourceManager.GetString("PropWrongTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For the element &apos;{0}&apos; no signals are mapped to a status type. ähnelt.
        /// </summary>
        internal static string StatusSigMapErr {
            get {
                return ResourceManager.GetString("StatusSigMapErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle identification number ähnelt.
        /// </summary>
        internal static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
    }
}
