//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Scheme.Sdk {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Scheme.Sdk.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Input Port ähnelt.
        /// </summary>
        internal static string AddInputPortMenu {
            get {
                return ResourceManager.GetString("AddInputPortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Output Port ähnelt.
        /// </summary>
        internal static string AddOutputPortMenu {
            get {
                return ResourceManager.GetString("AddOutputPortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Altitude ähnelt.
        /// </summary>
        internal static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property for the &apos;command&apos; of the element &apos;&apos; is not defined. ähnelt.
        /// </summary>
        internal static string CommandPropNotDef {
            get {
                return ResourceManager.GetString("CommandPropNotDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Constant ähnelt.
        /// </summary>
        internal static string Constant {
            get {
                return ResourceManager.GetString("Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A data file for runtime is expected. ähnelt.
        /// </summary>
        internal static string DataFileExpected {
            get {
                return ResourceManager.GetString("DataFileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A data file for the element &apos;{0} &apos; is expected. ähnelt.
        /// </summary>
        internal static string DataFileForPsExpected {
            get {
                return ResourceManager.GetString("DataFileForPsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data input port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string DataInPortNotConnectedErr {
            get {
                return ResourceManager.GetString("DataInPortNotConnectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data output port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string DataOutPortConError {
            get {
                return ResourceManager.GetString("DataOutPortConError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data output port of the element &apos;{0}&apos; don&apos;t have signals defined. ähnelt.
        /// </summary>
        internal static string DataOutPortSigError {
            get {
                return ResourceManager.GetString("DataOutPortSigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file or property expected. ähnelt.
        /// </summary>
        internal static string DataStorageFileErr {
            get {
                return ResourceManager.GetString("DataStorageFileErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Maximum of the output signal &apos;{0}&apos; must be greater as the Minimum. ähnelt.
        /// </summary>
        internal static string DefSigMinMaxErr {
            get {
                return ResourceManager.GetString("DefSigMinMaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An empty scheme is not valid. ähnelt.
        /// </summary>
        internal static string EmptySchemeErr {
            get {
                return ResourceManager.GetString("EmptySchemeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only a even frequency is supported ähnelt.
        /// </summary>
        internal static string EvenFreqErr {
            get {
                return ResourceManager.GetString("EvenFreqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exp - ähnelt.
        /// </summary>
        internal static string ExpMinus {
            get {
                return ResourceManager.GetString("ExpMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exp + ähnelt.
        /// </summary>
        internal static string ExpPlus {
            get {
                return ResourceManager.GetString("ExpPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generator ähnelt.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generator
        ///
        ///Generate signals from given functions. ähnelt.
        /// </summary>
        internal static string GeneratorPsDescription {
            get {
                return ResourceManager.GetString("GeneratorPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS
        ///
        ///Acquire data from a GPS device. ähnelt.
        /// </summary>
        internal static string GPSPsDescription {
            get {
                return ResourceManager.GetString("GPSPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Half round - ähnelt.
        /// </summary>
        internal static string HalfRoundMinus {
            get {
                return ResourceManager.GetString("HalfRoundMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Half round + ähnelt.
        /// </summary>
        internal static string HalfRoundPlus {
            get {
                return ResourceManager.GetString("HalfRoundPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mp-help.chm ähnelt.
        /// </summary>
        internal static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hour ähnelt.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The input port &apos;{0}&apos; of the element &apos;{1}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string InPortINotCon {
            get {
                return ResourceManager.GetString("InPortINotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid IP address. ähnelt.
        /// </summary>
        internal static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid password for the document. ähnelt.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The measurement comment for the element &apos;{0}&apos; is not defined. ähnelt.
        /// </summary>
        internal static string MeaCommentNotDef {
            get {
                return ResourceManager.GetString("MeaCommentNotDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Millisecond ähnelt.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; needs minimum one input and one output port. ähnelt.
        /// </summary>
        internal static string MinOnePortErr {
            get {
                return ResourceManager.GetString("MinOnePortErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minute ähnelt.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A memory of 0 is not supported. ähnelt.
        /// </summary>
        internal static string MPALMemSizeErr {
            get {
                return ResourceManager.GetString("MPALMemSizeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Noise ähnelt.
        /// </summary>
        internal static string Noise {
            get {
                return ResourceManager.GetString("Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; doesn&apos;t has a program loaded. ähnelt.
        /// </summary>
        internal static string NoProgLoadErr {
            get {
                return ResourceManager.GetString("NoProgLoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In block &apos;{0}&apos; no signal is mapped to a schema property. ähnelt.
        /// </summary>
        internal static string NoPropMapped {
            get {
                return ResourceManager.GetString("NoPropMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only numeric types can be assigned to a variable. ähnelt.
        /// </summary>
        internal static string NumVarTypeErr {
            get {
                return ResourceManager.GetString("NumVarTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port &apos;{0}&apos; of the element &apos;{1}&apos; don&apos;t have signals. ähnelt.
        /// </summary>
        internal static string OutPortINoSigErr {
            get {
                return ResourceManager.GetString("OutPortINoSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port &apos;{0}&apos; of the element &apos;{1}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string OutPortINotCon {
            get {
                return ResourceManager.GetString("OutPortINotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A periode of 0 is not defined. ähnelt.
        /// </summary>
        internal static string PeriodeErr {
            get {
                return ResourceManager.GetString("PeriodeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For post trigger time a positive number is expected. ähnelt.
        /// </summary>
        internal static string PostTriggerErr {
            get {
                return ResourceManager.GetString("PostTriggerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For pre trigger time a positive number is expected. ähnelt.
        /// </summary>
        internal static string PreTriggerErr {
            get {
                return ResourceManager.GetString("PreTriggerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The program couldn&apos;t be loaded. ähnelt.
        /// </summary>
        internal static string ProgLoadErr {
            get {
                return ResourceManager.GetString("ProgLoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program
        ///
        ///Execute a user defined program. ähnelt.
        /// </summary>
        internal static string ProgramPsDescription {
            get {
                return ResourceManager.GetString("ProgramPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property is not available. ähnelt.
        /// </summary>
        internal static string PropNotAvail {
            get {
                return ResourceManager.GetString("PropNotAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property &apos;{0}&apos; for the input variable of the element &apos;{1}&apos; is not available. ähnelt.
        /// </summary>
        internal static string PropNotAvailErr {
            get {
                return ResourceManager.GetString("PropNotAvailErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write the value of a property ähnelt.
        /// </summary>
        internal static string PropPsDescription {
            get {
                return ResourceManager.GetString("PropPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An instance of the element &apos;{0}&apos; is available. ähnelt.
        /// </summary>
        internal static string PsInstanceIsAviable {
            get {
                return ResourceManager.GetString("PsInstanceIsAviable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; couldn&apos;t be loaded. One or more modules are missing or  a vaild licence not found. ähnelt.
        /// </summary>
        internal static string PsLoadErr {
            get {
                return ResourceManager.GetString("PsLoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element type not definied. ähnelt.
        /// </summary>
        internal static string PsUndefined {
            get {
                return ResourceManager.GetString("PsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quality ähnelt.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rampe down ähnelt.
        /// </summary>
        internal static string RampDown {
            get {
                return ResourceManager.GetString("RampDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ramp up ähnelt.
        /// </summary>
        internal static string RampUp {
            get {
                return ResourceManager.GetString("RampUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random ähnelt.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Data ähnelt.
        /// </summary>
        internal static string ReadData {
            get {
                return ResourceManager.GetString("ReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Data
        ///
        ///Reads measurement data from a file. ähnelt.
        /// </summary>
        internal static string ReadDataPsDescription {
            get {
                return ResourceManager.GetString("ReadDataPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Parameter ähnelt.
        /// </summary>
        internal static string ReadProp {
            get {
                return ResourceManager.GetString("ReadProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Parameter
        ///
        ///Read a parameter.  ähnelt.
        /// </summary>
        internal static string ReadPropDesc {
            get {
                return ResourceManager.GetString("ReadPropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Square ähnelt.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove signals? ähnelt.
        /// </summary>
        internal static string RemoveSig {
            get {
                return ResourceManager.GetString("RemoveSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Unused Ports ähnelt.
        /// </summary>
        internal static string RemoveUnusedPortsMenu {
            get {
                return ResourceManager.GetString("RemoveUnusedPortsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type of the runtime engine is unknown. ähnelt.
        /// </summary>
        internal static string RtTypeUnknown {
            get {
                return ResourceManager.GetString("RtTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sample rate or periode is to small. ähnelt.
        /// </summary>
        internal static string SampleRatePerErr {
            get {
                return ResourceManager.GetString("SampleRatePerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Satellites used ähnelt.
        /// </summary>
        internal static string Satellites {
            get {
                return ResourceManager.GetString("Satellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Second ähnelt.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal &apos;{0}&apos; in the element &apos;{1}&apos; is more than once available as input. ähnelt.
        /// </summary>
        internal static string SigDupInInput {
            get {
                return ResourceManager.GetString("SigDupInInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal maximum must be greater than minimum. ähnelt.
        /// </summary>
        internal static string SigMinMaxErr {
            get {
                return ResourceManager.GetString("SigMinMaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die signal ähnelt.
        /// </summary>
        internal static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal must have a name. ähnelt.
        /// </summary>
        internal static string SignalNameErr {
            get {
                return ResourceManager.GetString("SignalNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die signals ähnelt.
        /// </summary>
        internal static string Signals {
            get {
                return ResourceManager.GetString("Signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal name &apos;{0}&apos; is duplicated. ähnelt.
        /// </summary>
        internal static string SigNameDup {
            get {
                return ResourceManager.GetString("SigNameDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal must have a name. ähnelt.
        /// </summary>
        internal static string SigNameErr {
            get {
                return ResourceManager.GetString("SigNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element {0} don&apos;t accespt signals of object type. ähnelt.
        /// </summary>
        internal static string SigObjetErr {
            get {
                return ResourceManager.GetString("SigObjetErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data type of the signal is not compatible to this variable. ähnelt.
        /// </summary>
        internal static string SigVarDataTypeErr {
            get {
                return ResourceManager.GetString("SigVarDataTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sine Cardinalis + ähnelt.
        /// </summary>
        internal static string Sinc {
            get {
                return ResourceManager.GetString("Sinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sine Cardinalis - ähnelt.
        /// </summary>
        internal static string SincMinus {
            get {
                return ResourceManager.GetString("SincMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sine ähnelt.
        /// </summary>
        internal static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sine - ähnelt.
        /// </summary>
        internal static string SineMinus {
            get {
                return ResourceManager.GetString("SineMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sine +  ähnelt.
        /// </summary>
        internal static string SinePlus {
            get {
                return ResourceManager.GetString("SinePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Splitter ähnelt.
        /// </summary>
        internal static string Splitter {
            get {
                return ResourceManager.GetString("Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Splitter
        ///
        ///Distributes the signals from input ports to output ports. ähnelt.
        /// </summary>
        internal static string SplitterPsDescription {
            get {
                return ResourceManager.GetString("SplitterPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop
        ///
        ///Stop the scheme execution. ähnelt.
        /// </summary>
        internal static string StopPsDescription {
            get {
                return ResourceManager.GetString("StopPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopwatch ähnelt.
        /// </summary>
        internal static string StopWatch {
            get {
                return ResourceManager.GetString("StopWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopwatch
        ///
        ///Stopwatch with start/stop trigger and reset input. ähnelt.
        /// </summary>
        internal static string StopWatchPsDescription {
            get {
                return ResourceManager.GetString("StopWatchPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The storage file for the element &apos;{0}&apos; is not defined. ähnelt.
        /// </summary>
        internal static string StorageFileNotDef {
            get {
                return ResourceManager.GetString("StorageFileNotDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Scheme ähnelt.
        /// </summary>
        internal static string SubScheme {
            get {
                return ResourceManager.GetString("SubScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscheme 
        ///
        ///Insert a Subscheme. ähnelt.
        /// </summary>
        internal static string SubschemePsDescription {
            get {
                return ResourceManager.GetString("SubschemePsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The timer resolution is 10ms. Only multiplier of 10 is supported as interval. ähnelt.
        /// </summary>
        internal static string TimerRes10Err {
            get {
                return ResourceManager.GetString("TimerRes10Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track angle ähnelt.
        /// </summary>
        internal static string TrackAngle {
            get {
                return ResourceManager.GetString("TrackAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; needs a trigger signal to execute the program. ähnelt.
        /// </summary>
        internal static string TriggerForProgErr {
            get {
                return ResourceManager.GetString("TriggerForProgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger input port of the element &apos;{0}&apos; expect minimum one input signal for this trigger type. ähnelt.
        /// </summary>
        internal static string TriggerOneSigErr {
            get {
                return ResourceManager.GetString("TriggerOneSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger port with start/stop trigger of the element &apos;{0}&apos; need two signal. ähnelt.
        /// </summary>
        internal static string TriggerPortNeed2SigErr {
            get {
                return ResourceManager.GetString("TriggerPortNeed2SigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger input port of the element &apos;{0}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string TriggerPortNotConErr {
            get {
                return ResourceManager.GetString("TriggerPortNotConErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger port of the element &apos;{0}&apos; don&apos;t have a signal. ähnelt.
        /// </summary>
        internal static string TriggerPortSigError {
            get {
                return ResourceManager.GetString("TriggerPortSigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A trigger signal is expected. ähnelt.
        /// </summary>
        internal static string TriggerSigExpectedErr {
            get {
                return ResourceManager.GetString("TriggerSigExpectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A time period for pre trigger and post trigger is expected. ähnelt.
        /// </summary>
        internal static string TriggerTimePerErr {
            get {
                return ResourceManager.GetString("TriggerTimePerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trigger input port of the element &apos;{0}&apos; expect minimum two input signals for this trigger type. ähnelt.
        /// </summary>
        internal static string TriggerTwoSigErr {
            get {
                return ResourceManager.GetString("TriggerTwoSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown document type. ähnelt.
        /// </summary>
        internal static string UnknownDocType {
            get {
                return ResourceManager.GetString("UnknownDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write Data ähnelt.
        /// </summary>
        internal static string WriteData {
            get {
                return ResourceManager.GetString("WriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write Data
        ///
        ///Write the measurement data into a file. ähnelt.
        /// </summary>
        internal static string WriteDataPsDescription {
            get {
                return ResourceManager.GetString("WriteDataPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write parameter ähnelt.
        /// </summary>
        internal static string WriteProp {
            get {
                return ResourceManager.GetString("WriteProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A generation rate of 0 is not supported. ähnelt.
        /// </summary>
        internal static string ZeroGenRateErr {
            get {
                return ResourceManager.GetString("ZeroGenRateErr", resourceCulture);
            }
        }
    }
}
