//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Mod.MPAL {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Mod.MPAL.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Input Port ähnelt.
        /// </summary>
        internal static string AddInputPortMenu {
            get {
                return ResourceManager.GetString("AddInputPortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Maximum of the output signal &apos;{0}&apos; must be greater as the Minimum. ähnelt.
        /// </summary>
        internal static string DefSigMinMaxErr {
            get {
                return ResourceManager.GetString("DefSigMinMaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid IP address. ähnelt.
        /// </summary>
        internal static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A memory of 0 is not supported. ähnelt.
        /// </summary>
        internal static string MPALMemSizeErr {
            get {
                return ResourceManager.GetString("MPALMemSizeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; doesn&apos;t has a program loaded. ähnelt.
        /// </summary>
        internal static string NoProgLoadErr {
            get {
                return ResourceManager.GetString("NoProgLoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only numeric types can be assigned to a variable. ähnelt.
        /// </summary>
        internal static string NumVarTypeErr {
            get {
                return ResourceManager.GetString("NumVarTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The program couldn&apos;t be loaded. ähnelt.
        /// </summary>
        internal static string ProgLoadErr {
            get {
                return ResourceManager.GetString("ProgLoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program
        ///
        ///Execute a user defined program. ähnelt.
        /// </summary>
        internal static string ProgramPsDescription {
            get {
                return ResourceManager.GetString("ProgramPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property &apos;{0}&apos; for the input variable of the element &apos;{1}&apos; is not available. ähnelt.
        /// </summary>
        internal static string PropNotAvailErr {
            get {
                return ResourceManager.GetString("PropNotAvailErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Unused Ports ähnelt.
        /// </summary>
        internal static string RemoveUnusedPortsMenu {
            get {
                return ResourceManager.GetString("RemoveUnusedPortsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data type of the signal is not compatible to this variable. ähnelt.
        /// </summary>
        internal static string SigVarDataTypeErr {
            get {
                return ResourceManager.GetString("SigVarDataTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; needs a trigger signal to execute the program. ähnelt.
        /// </summary>
        internal static string TriggerForProgErr {
            get {
                return ResourceManager.GetString("TriggerForProgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A trigger signal is expected. ähnelt.
        /// </summary>
        internal static string TriggerSigExpectedErr {
            get {
                return ResourceManager.GetString("TriggerSigExpectedErr", resourceCulture);
            }
        }
    }
}
