/*
 * Copyright (C) 2015 by Laurentiu-Gheorghe Crisan
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * As a special exception, you may use this file as part of a free
 * software library without restriction. Specifically, if other files
 * instantiate templates or use macros or inline functions from this
 * file, or you compile this file and link it with other files to
 * produce an executable, this file does not by itself cause the
 * resulting executable to be covered by the GNU General Public
 * License. This exception does not however invalidate any other
 * reasons why the executable file might be covered by the GNU Library
 * General Public License.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
#ifndef MPAL_VM_INSTRUCTIONCODE_H
#define MPAL_VM_INSTRUCTIONCODE_H

namespace mpal{
namespace vm{

    enum InstructionCode
    {
        NOP     = 0,
        AddSINT = 1,
        AddINT,
        AddDINT,
        AddLINT,
        AddUSINT,
        AddUINT,
        AddUDINT,
        AddULINT,
        AddREAL,
        AddLREAL,

        //SUB
        SubSINT,
        SubINT,
        SubDINT,
        SubLINT,
        SubUSINT,
        SubUINT,
        SubUDINT,
        SubULINT,
        SubREAL,
        SubLREAL,

        //MUL
        MulSINT,
        MulINT,
        MulDINT,
        MulLINT,
        MulUSINT,
        MulUINT,
        MulUDINT,
        MulULINT,
        MulREAL,
        MulLREAL,

        //MUL
        DivSINT,
        DivINT,
        DivDINT,
        DivLINT,
        DivUSINT,
        DivUINT,
        DivUDINT,
        DivULINT,
        DivREAL,
        DivLREAL,

        //Greater
        GrSINT,
        GrINT,
        GrDINT,
        GrLINT,
        GrUSINT,
        GrUINT,
        GrUDINT,
        GrULINT,
        GrREAL,
        GrLREAL,

        //Less
        LsSINT,
        LsINT,
        LsDINT,
        LsLINT,
        LsUSINT,
        LsUINT,
        LsUDINT,
        LsULINT,
        LsREAL,
        LsLREAL,

        //Greater or equal
        GeSINT,
        GeINT,
        GeDINT,
        GeLINT,
        GeUSINT,
        GeUINT,
        GeUDINT,
        GeULINT,
        GeREAL,
        GeLREAL,

        //Less or equal
        LeSINT,
        LeINT,
        LeDINT,
        LeLINT,
        LeUSINT,
        LeUINT,
        LeUDINT,
        LeULINT,
        LeREAL,
        LeLREAL,

        //Equal
        EqSINT,
        EqINT,
        EqDINT,
        EqLINT,
        EqUSINT,
        EqUINT,
        EqUDINT,
        EqULINT,
        EqREAL,
        EqLREAL,
        
        //Not equal
        NeSINT,
        NeINT,
        NeDINT,
        NeLINT,
        NeUSINT,
        NeUINT,
        NeUDINT,
        NeULINT,
        NeREAL,
        NeLREAL,

        //Move
        Move,

        //Stack handling
        PushTempOp,
        PopTempOp,
        PushRef,
        PopRef,

        //Offset handling
        AddOffsetSINT,
        AddOffsetINT,
        AddOffsetDINT,
        AddOffsetLINT,
        AddOffsetUSINT,
        AddOffsetUINT,
        AddOffsetUDINT,
        AddOffsetULINT,

        //Conversion
        BOOL2SINT,
        BOOL2INT,
        BOOL2DINT,
        BOOL2LINT,
        BOOL2USINT,
        BOOL2UINT,
        BOOL2UDINT,
        BOOL2ULINT,
        BOOL2REAL,
        BOOL2LREAL,
        BOOL2BYTE,
        BOOL2WORD,
        BOOL2DWORD,
        BOOL2LWORD,
        BOOL2STRING,
        BOOL2WSTRING,

        SINT2BOOL,
        SINT2INT,
        SINT2DINT,
        SINT2LINT,
        SINT2USINT,
        SINT2UINT,
        SINT2UDINT,
        SINT2ULINT,
        SINT2REAL,
        SINT2LREAL,
        SINT2STRING,
        SINT2BYTE,
        SINT2WORD,
        SINT2DWORD,
        SINT2LWORD,
        SINT2WSTRING,

        INT2BOOL,
        INT2SINT,
        INT2DINT,
        INT2LINT,
        INT2USINT,
        INT2UINT,
        INT2UDINT, 
        INT2ULINT,
        INT2REAL,
        INT2LREAL,
        INT2STRING,
        INT2BYTE,
        INT2WORD,
        INT2DWORD,
        INT2LWORD,
        INT2WSTRING,

        DINT2BOOL,
        DINT2LINT,
        DINT2USINT,
        DINT2UINT,
        DINT2UDINT,
        DINT2ULINT,
        DINT2REAL,
        DINT2LREAL,
        DINT2BYTE,
        DINT2WORD,        
        DINT2DWORD,
        DINT2LWORD,
        DINT2WSTRING,
        DINT2SINT,
        DINT2INT,
        DINT2STRING,
    
        LINT2BOOL,
        LINT2SINT,
        LINT2INT,
        LINT2DINT,
        LINT2USINT,
        LINT2UINT,
        LINT2ULINT,
        LINT2REAL,
        LINT2LREAL,
        LINT2STRING,
        LINT2BYTE,
        LINT2WORD,
        LINT2DWORD,
        LINT2LWORD,
        LINT2WSTRING,
        LINT2UDINT,

        USINT2BOOL,
        USINT2SINT,
        USINT2INT,
        USINT2DINT,
        USINT2LINT,
        USINT2UINT,
        USINT2UDINT,
        USINT2ULINT,
        USINT2REAL,
        USINT2LREAL,
        USINT2STRING,
        USINT2BYTE,
        USINT2WORD,
        USINT2DWORD,
        USINT2LWORD,
        USINT2WSTRING,

        UINT2BOOL,
        UINT2SINT,
        UINT2INT,
        UINT2DINT,
        UINT2LINT,
        UINT2USINT,
        UINT2UDINT,
        UINT2ULINT,
        UINT2REAL,
        UINT2LREAL,
        UINT2STRING,
        UINT2BYTE,
        UINT2WORD,
        UINT2DWORD,
        UINT2LWORD,
        UINT2WSTRING,

        UDINT2BOOL,
        UDINT2SINT,
        UDINT2INT,
        UDINT2DINT,
        UDINT2LINT,
        UDINT2USINT,
        UDINT2UINT,
        UDINT2ULINT,
        UDINT2REAL,
        UDINT2LREAL,
        UDINT2STRING,
        UDINT2BYTE,
        UDINT2WORD,
        UDINT2DWORD,
        UDINT2LWORD,
        UDINT2WSTRING,

        ULINT2BOOL,
        ULINT2SINT,
        ULINT2INT,
        ULINT2DINT,
        ULINT2LINT,
        ULINT2USINT,
        ULINT2UINT,
        ULINT2UDINT,
        ULINT2REAL,
        ULINT2LREAL,
        ULINT2STRING,
        ULINT2BYTE,
        ULINT2WORD,
        ULINT2DWORD,
        ULINT2LWORD,
        ULINT2WSTRING,

        REAL2BOOL,
        REAL2SINT,
        REAL2INT,
        REAL2DINT,
        REAL2LINT,
        REAL2USINT,
        REAL2UINT,
        REAL2UDINT,
        REAL2ULINT,
        REAL2LREAL,
        REAL2STRING,
        REAL2BYTE,
        REAL2WORD,
        REAL2DWORD,
        REAL2LWORD,
        REAL2WSTRING,

        LREAL2BOOL,
        LREAL2SINT,
        LREAL2INT,
        LREAL2DINT,
        LREAL2LINT,
        LREAL2USINT,
        LREAL2UINT,
        LREAL2UDINT,
        LREAL2ULINT,
        LREAL2REAL,
        LREAL2STRING,
        LREAL2BYTE,
        LREAL2WORD,
        LREAL2DWORD,
        LREAL2LWORD,
        LREAL2WSTRING,

        STRING2BOOL,
        STRING2SINT,
        STRING2INT,
        STRING2DINT,
        STRING2LINT,
        STRING2USINT,
        STRING2UINT,
        STRING2UDINT,
        STRING2ULINT,
        STRING2REAL,
        STRING2LREAL,
        STRING2BYTE,
        STRING2WORD,
        STRINGDWORD,
        STRING2LWORD,
        STRING2WSTRING,

        BYTE2BOOL,
        BYTE2SINT,
        BYTE2INT,
        BYTE2DINT,
        BYTE2LINT,
        BYTE2USINT,
        BYTE2UINT,
        BYTE2UDINT,
        BYTE2ULINT,
        BYTE2REAL,
        BYTE2LREAL,
        BYTE2STRING,
        BYTE2WORD,
        BYTE2DWORD,
        BYTE2LWORD,
        BYTE2WSTRING,

        WORD2BOOL,
        WORD2SINT,
        WORD2INT,
        WORD2DINT,
        WORD2LINT,
        WORD2USINT,
        WORD2UINT,
        WORD2UDINT,
        WORD2ULINT,
        WORD2REAL,
        WORD2LREAL,
        WORD2STRING,
        WORD2BYTE,
        WORD2DWORD,
        WORD2LWORD,
        WORD2WSTRING,

        DWORD2BOOL,
        DWORD2SINT,
        DWORD2INT,
        DWORD2DINT,
        DWORD2LINT,
        DWORD2USINT,
        DWORD2UINT,
        DWORD2UDINT,
        DWORD2ULINT,
        DWORD2REAL,
        DWORD2LREAL,
        DWORD2STRING,
        DWORD2BYTE,
        DWORD2WORD,
        DWORD2LWORD,
        DWORD2WSTRING,

        LWORD2BOOL,
        LWORD2SINT,
        LWORD2INT,
        LWORD2DINT,
        LWORD2LINT,
        LWORD2USINT,
        LWORD2UINT,
        LWORD2UDINT,
        LWORD2ULINT,
        LWORD2REAL,
        LWORD2LREAL,
        LWORD2STRING,
        LWORD2BYTE,
        LWORD2WORD,
        LWORD2DWORD,
        LWORD2WSTRING,

        WSTRING2BOOL,
        WSTRING2SINT,
        WSTRING2INT,
        WSTRING2DINT,
        WSTRING2LINT,
        WSTRING2USINT,
        WSTRING2UINT,
        WSTRING2UDINT,
        WSTRING2ULINT,
        WSTRING2REAL,
        WSTRING2LREAL,
        WSTRING2BYTE,
        WSTRING2WORD,
        WSTRING2DWORD,
        WSTRING2LWORD,

        //MOD
        ModSINT,
        ModINT,
        ModDINT,
        ModLINT,
        ModUSINT,
        ModUINT,
        ModUDINT,
        ModULINT,

        //Or
        OrBOOL,
        OrBYTE,
        OrWORD,
        OrDWORD,
        OrLWORD,

        //And
        AndBOOL,
        AndBYTE,
        AndWORD,
        AndDWORD,
        AndLWORD,

        //Xor
        XorBOOL,
        XorBYTE,
        XorWORD,
        XorDWORD,
        XorLWORD,

        //Pow
        PowSINT,
        PowINT,
        PowDINT,
        PowLINT,
        PowUSINT,
        PowUINT,
        PowUDINT,
        PowULINT,
        PowREAL,
        PowLREAL,

        //Not
        NotBOOL,

        //Neg
        NegSINT,
        NegINT,
        NegDINT,
        NegLINT,
        NegUSINT,
        NegUINT,
        NegUDINT,
        NegULINT,
        NegREAL,
        NegLREAL,

        JmpTRUE,
        JmpFALSE,
        Jmp,
        Return,

        //Inc
        IncSINT,
        IncINT,
        IncDINT,
        IncLINT,
        IncUSINT,
        IncUINT,
        IncUDINT,
        IncULINT,
        IncREAL,
        IncLREAL,

        //Dec
        DecSINT,
        DecINT,
        DecDINT,
        DecLINT,
        DecUSINT,
        DecUINT,
        DecUDINT,
        DecULINT,
        DecREAL,
        DecLREAL,

        //Floating point instructions
        Round,
        Trunc,

       //Abs
        AbsSINT,
        AbsINT,
        AbsDINT,
        AbsLINT,
        AbsREAL,
        AbsLREAL,

        //Sqr
        SqrSINT,
        SqrINT,
        SqrDINT,
        SqrLINT,
        SqrUSINT,
        SqrUINT,
        SqrUDINT,
        SqrULINT,
        SqrREAL,
        SqrLREAL,

        //Sqrt
        SqrtSINT,
        SqrtINT,
        SqrtDINT,
        SqrtLINT,
        SqrtUSINT,
        SqrtUINT,
        SqrtUDINT,
        SqrtULINT,
        SqrtREAL,
        SqrtLREAL,

        //Exp  e^n
        ExpSINT,
        ExpINT,
        ExpDINT,
        ExpLINT,
        ExpUSINT,
        ExpUINT,
        ExpUDINT,
        ExpULINT,
        ExpREAL,
        ExpLREAL,

        //Expd 10^n
        ExpdSINT,
        ExpdINT,
        ExpdDINT,
        ExpdLINT,
        ExpdUSINT,
        ExpdUINT,
        ExpdUDINT,
        ExpdULINT,
        ExpdREAL,
        ExpdLREAL,

        //LN
        LnSINT,
        LnINT,
        LnDINT,
        LnLINT,
        LnUSINT,
        LnUINT,
        LnUDINT,
        LnULINT,
        LnREAL,
        LnLREAL,

        //Log
        LogSINT,
        LogINT,
        LogDINT,
        LogLINT,
        LogUSINT,
        LogUINT,
        LogUDINT,
        LogULINT,
        LogREAL,
        LogLREAL,

        //ACos
        AcosSINT,
        AcosINT,
        AcosDINT,
        AcosLINT,
        AcosUSINT,
        AcosUINT,
        AcosUDINT,
        AcosULINT,
        AcosREAL,
        AcosLREAL,

        //ASin
        AsinSINT,
        AsinINT,
        AsinDINT,
        AsinLINT,
        AsinUSINT,
        AsinUINT,
        AsinUDINT,
        AsinULINT,
        AsinREAL,
        AsinLREAL,

        //Atan
        AtanSINT,
        AtanINT,
        AtanDINT,
        AtanLINT,
        AtanUSINT,
        AtanUINT,
        AtanUDINT,
        AtanULINT,
        AtanREAL,
        AtanLREAL,

        //Cos
        CosSINT,
        CosINT,
        CosDINT,
        CosLINT,
        CosUSINT,
        CosUINT,
        CosUDINT,
        CosULINT,
        CosREAL,
        CosLREAL,

        //Sin
        SinSINT,
        SinINT,
        SinDINT,
        SinLINT,
        SinUSINT,
        SinUINT,
        SinUDINT,
        SinULINT,
        SinREAL,
        SinLREAL,

        //Sin
        TanSINT,
        TanINT,
        TanDINT,
        TanLINT,
        TanUSINT,
        TanUINT,
        TanUDINT,
        TanULINT,
        TanREAL,
        TanLREAL,

        //Rotate left
        RolBYTE,
        RolWORD,
        RolDWORD,
        RolLWORD,

        //Rotate right
        RorBYTE,
        RorWORD,
        RorDWORD,
        RorLWORD,

        //Shift left
        ShlBYTE,
        ShlWORD,
        ShlDWORD,
        ShlLWORD,

        //Shift right
        ShrBYTE,
        ShrWORD,
        ShrDWORD,
        ShrLWORD,

        Call,

        Sel,

       //Max,
        MaxSINT,
        MaxINT,
        MaxDINT,
        MaxLINT,
        MaxUSINT,
        MaxUINT,
        MaxUDINT,
        MaxULINT,
        MaxREAL,
        MaxLREAL,

        //Min,
        MinSINT,
        MinINT,
        MinDINT,
        MinLINT,
        MinUSINT,
        MinUINT,
        MinUDINT,
        MinULINT,
        MinREAL,
        MinLREAL,

        //Limit
        LimitSINT,
        LimitINT,
        LimitDINT,
        LimitLINT,
        LimitUSINT,
        LimitUINT,
        LimitUDINT,
        LimitULINT,
        LimitREAL,
        LimitLREAL,

        //Mux
        MuxSINT,
        MuxINT,
        MuxDINT,
        MuxLINT,
        MuxUSINT,
        MuxUINT,
        MuxUDINT,
        MuxULINT,
    };
}}

#endif

