//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Mod.CAN {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Mod.CAN.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit count: ähnelt.
        /// </summary>
        internal static string BitCount {
            get {
                return ResourceManager.GetString("BitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal is not in the message bit range. ähnelt.
        /// </summary>
        internal static string BitRangeErr {
            get {
                return ResourceManager.GetString("BitRangeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum of the message byte count is 8. ähnelt.
        /// </summary>
        internal static string ByteCountErr {
            get {
                return ResourceManager.GetString("ByteCountErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Byte count: ähnelt.
        /// </summary>
        internal static string ByteCout {
            get {
                return ResourceManager.GetString("ByteCout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Byte order: ähnelt.
        /// </summary>
        internal static string ByteOrder {
            get {
                return ResourceManager.GetString("ByteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Bus ähnelt.
        /// </summary>
        internal static string CANBus {
            get {
                return ResourceManager.GetString("CANBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Data ähnelt.
        /// </summary>
        internal static string CANData {
            get {
                return ResourceManager.GetString("CANData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Event ähnelt.
        /// </summary>
        internal static string CANEventPS {
            get {
                return ResourceManager.GetString("CANEventPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Event
        ///
        ///Sends a CAN message if an event occurs. ähnelt.
        /// </summary>
        internal static string CANEventPsDescription {
            get {
                return ResourceManager.GetString("CANEventPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Input ähnelt.
        /// </summary>
        internal static string CANInput {
            get {
                return ResourceManager.GetString("CANInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Input
        ///
        ///Acquire measurement data from CAN bus. (CANdb) ähnelt.
        /// </summary>
        internal static string CANInputPsDescription {
            get {
                return ResourceManager.GetString("CANInputPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Read ähnelt.
        /// </summary>
        internal static string CANLogger {
            get {
                return ResourceManager.GetString("CANLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Read
        ///
        ///Acquire CAN message in raw format. ähnelt.
        /// </summary>
        internal static string CANLoggerPsDescription {
            get {
                return ResourceManager.GetString("CANLoggerPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Message View ähnelt.
        /// </summary>
        internal static string CANMessageView {
            get {
                return ResourceManager.GetString("CANMessageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; doesn&apos;t have signals mapped to the CAN output. ähnelt.
        /// </summary>
        internal static string CANOutError {
            get {
                return ResourceManager.GetString("CANOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Output ähnelt.
        /// </summary>
        internal static string CANOutput {
            get {
                return ResourceManager.GetString("CANOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Output
        ///
        ///Sends measurement data via CAN bus. (CANdb) ähnelt.
        /// </summary>
        internal static string CANOutputPsDescription {
            get {
                return ResourceManager.GetString("CANOutputPsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Write ähnelt.
        /// </summary>
        internal static string CANWrite {
            get {
                return ResourceManager.GetString("CANWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN Write
        ///
        ///Write a CAN message on the bus. ähnelt.
        /// </summary>
        internal static string CANWritePsDescription {
            get {
                return ResourceManager.GetString("CANWritePsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data type: ähnelt.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The factor must be greater as 0. ähnelt.
        /// </summary>
        internal static string FactorErr {
            get {
                return ResourceManager.GetString("FactorErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identifier ähnelt.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string MenuProperty {
            get {
                return ResourceManager.GetString("MenuProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum must be greater as minimum. ähnelt.
        /// </summary>
        internal static string MinMaxErr {
            get {
                return ResourceManager.GetString("MinMaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode value: ähnelt.
        /// </summary>
        internal static string ModeValue {
            get {
                return ResourceManager.GetString("ModeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signal &apos;{0}&apos; is mode depended but a mode signal in the message &apos;{1}&apos; is not defined. ähnelt.
        /// </summary>
        internal static string ModSignalErr {
            get {
                return ResourceManager.GetString("ModSignalErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element &apos;{0}&apos; don&apos;t have events defined. ähnelt.
        /// </summary>
        internal static string NoEventErr {
            get {
                return ResourceManager.GetString("NoEventErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A bit rate of 0 is not supported. ähnelt.
        /// </summary>
        internal static string NullBitrateErr {
            get {
                return ResourceManager.GetString("NullBitrateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A sample rate of 0 is not supported. ähnelt.
        /// </summary>
        internal static string NullRateErr {
            get {
                return ResourceManager.GetString("NullRateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port &apos;{0}&apos; of the element &apos;{1}&apos; is not connected. ähnelt.
        /// </summary>
        internal static string OutPortINotCon {
            get {
                return ResourceManager.GetString("OutPortINotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output ports of the element &apos;{0}&apos; are not connected. ähnelt.
        /// </summary>
        internal static string OutPortNotCon {
            get {
                return ResourceManager.GetString("OutPortNotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output port of the element &apos;{0}&apos; don&apos;t have signals. ähnelt.
        /// </summary>
        internal static string OutPortSigErr {
            get {
                return ResourceManager.GetString("OutPortSigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A output rate of 0 is not supported. ähnelt.
        /// </summary>
        internal static string OutRateNullErr {
            get {
                return ResourceManager.GetString("OutRateNullErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pivot bit: ähnelt.
        /// </summary>
        internal static string PivotBit {
            get {
                return ResourceManager.GetString("PivotBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For the element &apos;{0}&apos; no signals are mapped to a signal type. ähnelt.
        /// </summary>
        internal static string PSSigMap {
            get {
                return ResourceManager.GetString("PSSigMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} signal found. ähnelt.
        /// </summary>
        internal static string SignalFound {
            get {
                return ResourceManager.GetString("SignalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signals ähnelt.
        /// </summary>
        internal static string Signals {
            get {
                return ResourceManager.GetString("Signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} signals found. ähnelt.
        /// </summary>
        internal static string SignalsFound {
            get {
                return ResourceManager.GetString("SignalsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp and Identifier signals must be mapped. ähnelt.
        /// </summary>
        internal static string TimeAndIDNotMapped {
            get {
                return ResourceManager.GetString("TimeAndIDNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time stamp: ähnelt.
        /// </summary>
        internal static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type: ähnelt.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time stamp (10 µs res.) ähnelt.
        /// </summary>
        internal static string TypeTimeStamp {
            get {
                return ResourceManager.GetString("TypeTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit: ähnelt.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported signal data type for CAN message data. Expected 64 bit unsigned integer. ähnelt.
        /// </summary>
        internal static string UnsupDataType {
            get {
                return ResourceManager.GetString("UnsupDataType", resourceCulture);
            }
        }
    }
}
